# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PPM-Profile
version:      1.1
version_from: bin/ppmprofile.pl
installdirs:  site
requires:
    File::Temp:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
    PPM::UI:                       3
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
